version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "21:00"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: postcss
        versions:
          - 8.2.7
      - dependency-name: eslint-config-welly
        versions:
          - 1.8.15
      - dependency-name: ts-jest
        versions:
          - 26.5.3
      - dependency-name: husky
        versions:
          - 5.0.9
          - 5.1.1
      - dependency-name: "@rollup/plugin-node-resolve"
        versions:
          - 11.1.0
          - 11.1.1
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "21:00"
    open-pull-requests-limit: 10
